"""initk

Revision ID: 995e8abd8eac
Revises: 036
Create Date: 2026-03-16 23:39:40.743497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995e8abd8eac'
down_revision: Union[str, None] = '036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema='transaction') as batch_op:
        batch_op.drop_constraint(batch_op.f('bank_accounts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='user')
        batch_op.drop_column('account_number_confirmation')
        batch_op.drop_column('pix_key_confirmation')
        batch_op.drop_column('cci_number_confirmation')

    with op.batch_alter_table('coupons', schema='transaction') as batch_op:
        batch_op.drop_constraint(batch_op.f('coupons_code_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_transaction_coupons_code'))
        batch_op.create_index(batch_op.f('ix_transaction_coupons_code'), ['code'], unique=True)

    with op.batch_alter_table('transactions', schema='transaction') as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('tax_rate_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('commission_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('origin_amount',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
        batch_op.alter_column('destination_amount',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_transactions_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='user')

    with op.batch_alter_table('auth_login', schema='user') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user', schema='user') as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_document_number'))
        batch_op.drop_index(batch_op.f('ix_user_user_email'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['document_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema='user') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_user_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_user_document_number'), ['document_number'], unique=True)

    with op.batch_alter_table('auth_login', schema='user') as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('transactions', schema='transaction') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('destination_amount',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
        batch_op.alter_column('origin_amount',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
        batch_op.alter_column('commission_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('tax_rate_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('coupons', schema='transaction') as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_coupons_code'))
        batch_op.create_index(batch_op.f('ix_transaction_coupons_code'), ['code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('coupons_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('bank_accounts', schema='transaction') as batch_op:
        batch_op.add_column(sa.Column('cci_number_confirmation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pix_key_confirmation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_number_confirmation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bank_accounts_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
