# app/core/container.py
# Re-exporta desde containers/ para compatibilidad con imports existentes.
from app.core.containers import (
    get_security_utils,
    get_auth_repository,
    get_user_repository,
    get_user_by_id_uc,
    get_user_by_email_uc,
    get_user_by_auth_id_uc,
    create_user_uc,
    list_user_name_uc,
    list_users_uc,
    list_users_with_details_uc,
    update_user_uc,
    delete_user_uc,
    get_login_uc,
    get_auth_service,
    get_unit_of_work,
    get_tax_rate_repository,
    get_commission_repository,
    get_tax_rate_by_id_uc,
    list_tax_rates_uc,
    create_tax_rate_uc,
    update_tax_rate_uc,
    delete_tax_rate_uc,
    get_commission_by_id_uc,
    list_commissions_uc,
    create_commission_uc,
    update_commission_uc,
    delete_commission_uc,
)

__all__ = [
    "get_security_utils",
    "get_auth_repository",
    "get_user_repository",
    "get_user_by_id_uc",
    "get_user_by_email_uc",
    "get_user_by_auth_id_uc",
    "create_user_uc",
    "list_user_name_uc",
    "list_users_uc",
    "list_users_with_details_uc",
    "update_user_uc",
    "delete_user_uc",
    "get_login_uc",
    "get_auth_service",
    "get_unit_of_work",
    "get_tax_rate_repository",
    "get_commission_repository",
    "get_tax_rate_by_id_uc",
    "list_tax_rates_uc",
    "create_tax_rate_uc",
    "update_tax_rate_uc",
    "delete_tax_rate_uc",
    "get_commission_by_id_uc",
    "list_commissions_uc",
    "create_commission_uc",
    "update_commission_uc",
    "delete_commission_uc",
]

# Alias usado en algún código
user_repo = get_user_repository
